STATUS_UPLOADED = "UPLOADED"
STATUS_PROCESSING = "PROCESSING"
STATUS_COMPLETED = "COMPLETED"
STATUS_FAILED = "FAILED"

DEFAULT_ALLOWED_DOCUMENT_TYPES = ("resume", "invoice", "general")
DEFAULT_MAX_CONTENT_LENGTH = 10 * 1024 * 1024
DEFAULT_UPLOAD_PREFIX = "uploads/"
DEFAULT_UPLOAD_URL_EXPIRATION_SECONDS = 900
DEFAULT_RECORD_TTL_DAYS = 7
DEFAULT_EXTRACTED_TEXT_PREVIEW_LENGTH = 1000
DEFAULT_BEDROCK_TEXT_LIMIT = 12000
DEFAULT_STALE_PROCESSING_SECONDS = 600
DEFAULT_MAX_TEXTRACT_PAGES = 25
